name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Convert to gzipped tarball
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build
          tar -czvf github-pages.tar.gz dist/

      - name: Publish generated content to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
